;Animal Crossing New Horizons NookPhone Launcher
;By @Lfgberg#6323

;In order to customize the programs that are launched by the nookphone, please edit the following variables
;Apps are numbered from left to right, there are 5 rows of 3 apps for a total of 15 possible programs
;This means that App 8 is displayed on the third row and second column, App 13 is on the fifth row and first column and so on and so forth

[Variables]
;Replace AppImage with the file path of an icon you'd like to display
;To make a new icon please edit either placeholder-icon.png or placeholder-icon.pdn in the images folder so that everything alligns properly
;There are some example icons in the Images folder, feel free to use them
AppImage=#@#Images\placeholder-icon.png
;Replace AppPath with the file path of your program
AppName=NookPhone
;Replace AppPath with the file path of your program
AppPath=C:\

App2Image=#@#Images\placeholder-icon.png
App2Name=NookPhone
App2Path=C:\

App3Image=#@#Images\placeholder-icon.png
App3Name=NookPhone
App3Path=C:\

App4Image=#@#Images\placeholder-icon.png
App4Name=NookPhone
App4Path=C:\

App5Image=#@#Images\placeholder-icon.png
App5Name=NookPhone
App5Path=C:\

App6Image=#@#Images\placeholder-icon.png
App6Name=NookPhone
App6Path=C:\

App7Image=#@#Images\placeholder-icon.png
App7Name=NookPhone
App7Path=C:\

App8Image=#@#Images\placeholder-icon.png
App8Name=NookPhone
App8Path=C:\

App9Image=#@#Images\placeholder-icon.png
App9Name=NookPhone
App9Path=C:\

App10Image=#@#Images\placeholder-icon.png
App10Name=NookPhone
App10Path=C:\

App11Image=#@#Images\placeholder-icon.png
App11Name=NookPhone
App11Path=C:\

App12Image=#@#Images\placeholder-icon.png
App12Name=NookPhone
App12Path=C:\

App13Image=#@#Images\placeholder-icon.png
App13Name=NookPhone
App13Path=C:\

App14Image=#@#Images\placeholder-icon.png
App14Name=NookPhone
App14Path=C:\

App15Image=#@#Images\placeholder-icon.png
App15Name=NookPhone
App15Path=C:\
