[Variables]
;_   _             _    _____  _                       _____      _   _   _
;| \ | |           | |  |  __ \| |                     / ____|    | | | | (_)
;|  \| | ___   ___ | | _| |__) | |__   ___  _ __   ___| (___   ___| |_| |_ _ _ __   __ _ ___
;| . ` |/ _ \ / _ \| |/ /  ___/| '_ \ / _ \| '_ \ / _ \\___ \ / _ \ __| __| | '_ \ / _` / __|
;| |\  | (_) | (_) |   <| |    | | | | (_) | | | |  __/____) |  __/ |_| |_| | | | | (_| \__ \
;|_| \_|\___/ \___/|_|\_\_|    |_| |_|\___/|_| |_|\___|_____/ \___|\__|\__|_|_| |_|\__, |___/
;                                                                                  __/ |
;                                                                                 |___/

;Set ToggleOutline to either 0/1, default is 1 which enables an outline when you hover over an app, 0 disables this feature
ToggleOutline=1

;In order to customize the programs that are launched by the nookphone, please edit the following variables
;Apps are numbered from left to right, there are 5 rows of 3 apps for a total of 15 possible programs
;This means that App 8 is displayed on the third row and second column, App 13 is on the fifth row and first column and so on and so forth

;Replace AppImage with the file path of an icon you'd like to display
;To make a new icon please edit either placeholder-icon.png or placeholder-icon.pdn in the images folder so that everything alligns properly
;There are some example icons in the Images folder, feel free to use them
;If you make your own icon, either provide it's path, OR put it in the images folder and reference it with #@#Images\YourIconName.png
;Replace AppPath with the file path of your program
;Replace AppPath with the file path of your program
AppImage=#@#Images\placeholder-icon.png
AppName=NookPhone
AppPath=C:\

App2Image=#@#Images\placeholder-icon.png
App2Name=NookPhone
App2Path=C:\

App3Image=#@#Images\placeholder-icon.png
App3Name=NookPhone
App3Path=C:\

App4Image=#@#Images\placeholder-icon.png
App4Name=NookPhone
App4Path=C:\

App5Image=#@#Images\placeholder-icon.png
App5Name=NookPhone
App5Path=C:\

App6Image=#@#Images\placeholder-icon.png
App6Name=NookPhone
App6Path=C:\

App7Image=#@#Images\placeholder-icon.png
App7Name=NookPhone
App7Path=C:\

App8Image=#@#Images\placeholder-icon.png
App8Name=NookPhone
App8Path=C:\

App9Image=#@#Images\placeholder-icon.png
App9Name=NookPhone
App9Path=C:\

App10Image=#@#Images\placeholder-icon.png
App10Name=NookPhone
App10Path=C:\

App11Image=#@#Images\placeholder-icon.png
App11Name=NookPhone
App11Path=C:\

App12Image=#@#Images\placeholder-icon.png
App12Name=NookPhone
App12Path=C:\

App13Image=#@#Images\placeholder-icon.png
App13Name=NookPhone
App13Path=C:\

App14Image=#@#Images\placeholder-icon.png
App14Name=NookPhone
App14Path=C:\

App15Image=#@#Images\placeholder-icon.png
App15Name=NookPhone
App15Path=C:\
