[App]
MouseOverAction=[!SetOption SelectedApp Text "#AppName#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App2]
MouseOverAction=[!SetOption SelectedApp Text "#App2Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App3]
MouseOverAction=[!SetOption SelectedApp Text "#App3Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App4]
MouseOverAction=[!SetOption SelectedApp Text "#App4Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App5]
MouseOverAction=[!SetOption SelectedApp Text "#App5Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App6]
MouseOverAction=[!SetOption SelectedApp Text "#App6Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App7]
MouseOverAction=[!SetOption SelectedApp Text "#App7Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App8]

MouseOverAction=[!SetOption SelectedApp Text "#App8Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App9]
MouseOverAction=[!SetOption SelectedApp Text "#App9Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App10]
MouseOverAction=[!SetOption SelectedApp Text "#App10Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App11]
MouseOverAction=[!SetOption SelectedApp Text "#App11Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App12]
MouseOverAction=[!SetOption SelectedApp Text "#App12Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App13]
MouseOverAction=[!SetOption SelectedApp Text "#App13Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App14]
MouseOverAction=[!SetOption SelectedApp Text "#App14Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]

[App15]
MouseOverAction=[!SetOption SelectedApp Text "#App15Name#"][!UpdateMeter SelectedApp][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"]
