[App]
MouseOverAction=[!SetOption SelectedApp Text "#AppName#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App2]
MouseOverAction=[!SetOption SelectedApp Text "#App2Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App3]
MouseOverAction=[!SetOption SelectedApp Text "#App3Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App4]
MouseOverAction=[!SetOption SelectedApp Text "#App4Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App5]
MouseOverAction=[!SetOption SelectedApp Text "#App5Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App6]
MouseOverAction=[!SetOption SelectedApp Text "#App6Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App7]
MouseOverAction=[!SetOption SelectedApp Text "#App7Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App8]
MouseOverAction=[!SetOption SelectedApp Text "#App8Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App9]
MouseOverAction=[!SetOption SelectedApp Text "#App9Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App10]
MouseOverAction=[!SetOption SelectedApp Text "#App10Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App11]
MouseOverAction=[!SetOption SelectedApp Text "#App11Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App12]
MouseOverAction=[!SetOption SelectedApp Text "#App12Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App13]
MouseOverAction=[!SetOption SelectedApp Text "#App13Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App14]
MouseOverAction=[!SetOption SelectedApp Text "#App14Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]

[App15]
MouseOverAction=[!SetOption SelectedApp Text "#App15Name#"][!SetOption Outline MyModifiers "Stroke Color #AppColor#"][!SetOption Outline X "[[#CURRENTSECTION]:X]"][!SetOption Outline Y "[[#CURRENTSECTION]:Y]"][!UpdateMeter Outline][!Redraw]
MouseLeaveAction=[!SetOption SelectedApp Text "NookPhone"][!SetOption Outline MyModifiers "Stroke Color 0,0,0,0"][!UpdateMeter Outline][!Redraw]
